const seedUsers = [
  {"email":"acastagnier0@posterous.com","password":"IfW87tud3","firstName":"Alexis","lastName":"Castagnier"},
  {"email":"pcosgrave1@sciencedaily.com","password":"qexjP2I7kS","firstName":"Patience","lastName":"Cosgrave"},
  {"email":"abignold2@hp.com","password":"XTme1L","firstName":"Arluene","lastName":"Bignold"},
  {"email":"bdaldry3@shop-pro.jp","password":"PVueIE4","firstName":"Byrann","lastName":"Daldry"},
  {"email":"jcudby4@plala.or.jp","password":"cSmImyro8q","firstName":"Jerome","lastName":"Cudby"},
  {"email":"lvinten5@msu.edu","password":"w42j4N","firstName":"Lek","lastName":"Vinten"},
  {"email":"sandriolli6@wunderground.com","password":"oZFn2hd","firstName":"Starlene","lastName":"Andriolli"},
  {"email":"chudless7@tinyurl.com","password":"rvmdQFvb8adO","firstName":"Chrissie","lastName":"Hudless"},
  {"email":"dabbate8@usatoday.com","password":"ws5YhZTaCA0l","firstName":"Dukie","lastName":"Abbate"},
  {"email":"rwagnerin9@mayoclinic.com","password":"VfnqhuqzUR","firstName":"Rebeca","lastName":"Wagnerin"},
  {"email":"rguillarda@nbcnews.com","password":"gaSrRH19","firstName":"Rivkah","lastName":"Guillard"},
  {"email":"mbaglanb@clickbank.net","password":"MMTEHL","firstName":"Milka","lastName":"Baglan"},
  {"email":"tlintotc@people.com.cn","password":"GY9YFxRfA8","firstName":"Temp","lastName":"Lintot"},
  {"email":"rbusbyd@bloglovin.com","password":"WhdlkbmqL","firstName":"Ruby","lastName":"Busby"},
  {"email":"aknottleye@cbsnews.com","password":"GIN2YoIdlw","firstName":"Angeline","lastName":"Knottley"},
  {"email":"edowngatef@xing.com","password":"1oXzdX","firstName":"Elna","lastName":"Downgate"},
  {"email":"jbyllamg@infoseek.co.jp","password":"HjcRsOJ5Xus","firstName":"Judi","lastName":"Byllam"},
  {"email":"sshortanh@blogger.com","password":"kTOhWV","firstName":"Say","lastName":"Shortan"},
  {"email":"bcalytoni@nature.com","password":"aXbukVXUTWM","firstName":"Becca","lastName":"Calyton"},
  {"email":"otissellj@illinois.edu","password":"P0RiAonG","firstName":"Oberon","lastName":"Tissell"},
  {"email":"fshirilk@yellowpages.com","password":"94m4ngW","firstName":"Francis","lastName":"Shiril"},
  {"email":"lscroobyl@artisteer.com","password":"tU2MoA7","firstName":"Livvyy","lastName":"Scrooby"},
  {"email":"rcurrerm@house.gov","password":"E0gKC58y4wW","firstName":"Roosevelt","lastName":"Currer"},
  {"email":"ispringtorpn@netvibes.com","password":"1f7VoCO0pjy","firstName":"Irita","lastName":"Springtorp"},
  {"email":"danneslieo@statcounter.com","password":"pEtNeuIr","firstName":"Drusy","lastName":"Anneslie"},
  {"email":"mferedayp@twitpic.com","password":"fKsZdk9Z","firstName":"Mattheus","lastName":"Fereday"},
  {"email":"gcumberbatchq@nydailynews.com","password":"Y7eyBGcCPne","firstName":"Guido","lastName":"Cumberbatch"},
  {"email":"bdashkovr@cisco.com","password":"Fdcx1kZfSDAB","firstName":"Brook","lastName":"Dashkov"},
  {"email":"rtilberrys@networksolutions.com","password":"o3R3gkoadY","firstName":"Rosco","lastName":"Tilberry"},
  {"email":"usarrat@who.int","password":"t1pxPvtb7","firstName":"Ulrike","lastName":"Sarra"}
]

module.exports = seedUsers
